### ISSUE TITLE
[TicWatch Pro] 404 Not Found

### ISSUE THREAD

**Issue by romalibert** [AsteroidOS/asteroidos.org#136]
Hello, how do I download the firmware for TicWatch Pro?

**Comment by eLtMosen** [comment]
The port for catfish is very fresh and is not yet in the nightly build directories.
https://release.asteroidos.org/nightlies/

Sorry for the inconvenience.
Just to explain, we had a rush of Website improvements last week and the TicWatch Pro install instructions thus went online prematurely.

You will very likely be able to get an early image from the porters when asking on the AsteroidOS Matrix Channel.
#asteroid:matrix.org

**Comment by jrtberlin** [comment]
@romalibert the catfish (TicWatch Pro) build was not enabled on our server. I changed that and the image for it should be available in a few hours.

**Comment by jrtberlin** [comment]
Sorry, it took a bit longer. I had to fix another build on the way.
The images are now available here: https://release.asteroidos.org/nightlies/catfish/
