### ISSUE TITLE
Freedom & Privacy

### ISSUE THREAD

**Issue by kratz00** [AsteroidOS/asteroidos.org#19]
... this is what it says on your homepage regarding the wearable devices.
Regarding privacy, why is it that your homepage does requests to google-analytics.com and ajax.googleapis.com. There some other requests to CDNs as well. All of them are probably not protecting the privacy of your visitors.

**Comment by FlorentRevest** [comment]
I'm glad AsteroidOS has community members who care about their privacy as much as you do @kratz00 .
Thankfully the whole project is open to contributions, including this website. I would warmly welcome a pull request replacing the services provided by the CDNs we currently rely on.
