### ISSUE TITLE
Integrate model/product code and possibly more differentiating details for all watches

### ISSUE THREAD

**Issue by eLtMosen** [AsteroidOS/asteroidos.org#193]
Currently, only some install pages have the product code of a watch mentioned in not so prominent place.
Product code however
- Help users identify the watch exactly when purchasing
- Free SEO regrading requests for product codes from search engines.
- Generally give more detailed info on the watches and act as trusted source in the matter.

Lets discuss where to put this specific info. And possibly how to extend it to other details that differ between models like strap width and casing size.

This just to start off the product code collection, please do not mind the formating at all and ideally past your corrections in a better formated list :sweat_smile: 

:heavy_check_mark: W100 = dory [LG G Watch]
:heavy_check_mark: W110 = lenok [LG G Watch R]
:heavy_check_mark: W150 = bass [LG G Watch Urbane]
:heavy_check_mark:LM-W315 = narwhal [LG Watch W7]

:heavy_check_mark: 360L = smelt [Moto 360 2nd gen, 46mm, 20mm]
:heavy_check_mark: 360S = carp [Moto 360 2nd gen, 42mm, 18mm]
:heavy_check_mark: 360W = carp [Moto 360 2nd gen, 42mm, 16mm]
:heavy_check_mark: 360SP = sportscarp [Moto 360 sports]

:heavy_check_mark: WF11018 = catfish-ext [TicWatch Pro LTE]
:heavy_check_mark: WF12096 = catfish [TicWatch Pro]
:heavy_check_mark: WF12106 = catshark [TicWatch Pro 2020]
:heavy_check_mark: WG12016 = tunny [TicWatch S2]
:heavy_check_mark: WG12036 = skipjack [TicWatch C2/C2+]
:heavy_check_mark: WF12086 = mooneye [TicWatch E]
:heavy_check_mark: WF12066 = mooneye [TicWatch S]

:heavy_check_mark: WI500Q = anthias [Asus ZenWatch]
:heavy_check_mark: WI501Q = sparrow [Asus ZenWatch 2, 46mm]
:heavy_check_mark: WI502Q = wren [Asus ZenWatch 2, 41mm]
:heavy_check_mark: WI503Q = swift [Asus ZenWatch 3]

:heavy_check_mark: LEO-BX9 = Sawfish [Huawei Watch 2]
:heavy_check_mark: LEO-DLXX = Sawshark [Huawei Watch 2 LTE]

:heavy_check_mark: DW6F1 = firefish [Fossil Gen4]
:heavy_check_mark: DW7F1 = ray [Fossil Gen4]

:heavy_check_mark: OW19W6 = beluga [OPPO Watch 41mm WiFi]
:heavy_check_mark: OW19W8 = beluga [OPPO Watch 46mm Wifi]
:heavy_check_mark: OW19W12 (untested) = belugaxl [OPPO Watch 46mm LTE]
:heavy_check_mark: SWR50 = tetra [Sony Smartwatch 3]
:heavy_check_mark: SM-R382 = sprat [Samsung Gear Live]

:heavy_check_mark: W1 = sturgeon [Huawei Watch]
:heavy_check_mark: DW6xx & DW7xx = ray and firefish [Fossil gen4]

To be cleared:
- minnow [moto 360 gen 1]
- harmony and inharmony based watches still missing details

**Comment by beroset** [comment]
ZW10 = platy [ZTE Quartz]
LG-W200A = nemo [LG Watch Urbane 2nd Edition AT&T] See https://www.lg.com/us/smart-watches/lg-W200A-lg-watch-urbane-2nd-edition-att

**Comment by eLtMosen** [comment]
Closing, since the incentive to edit new watches model numbers into the site directly, from the model numbers now being displayed on the page.
