### ISSUE TITLE
Replace ClockworkMod UniversalAdbDriver with official google issued Android Platform-Tools ADB driver

### ISSUE THREAD

**Issue by eLtMosen** [AsteroidOS/asteroidos.org#203]
Two users now reported the Windows ADB driver we link too does not work anymore. For one user, the official google platform-tools driver worked. The other case still in testing as i am writing this.

Problems is, where to find a linkable source for a compiled version of the driver.
Thats not from some shady google docs folder like this one:
https://drive.google.com/drive/folders/1H8DxaRta8gafcUA8bJqkajobnnfuw2et

**Comment by E-Gwen** [comment]
Hi,

Unforntunately, both 32 & 64 bit adb drivers won't recognized the Asus Zen Watch 2 sparrow model I try to flash with AsteroidOS.
So it seems I can't go further at this time.
Ouf of ideas.

**Comment by E-Gwen** [comment]
Hey, wait a minute 👍 
I downloaded the Asus adb driver here, https://drivers.softpedia.com/get/MOBILES/ASUS/ASUS-Android-ADB-Interface-Driver-8003-for-Windows-10.shtml, installed them,
and now I can access the menu to unlock the bootloader.

But when i wrote the flash image line, i get this error message : 
"cannot determine image filename for 'C:\Users\Gwen\asteroid-image-sparrow.ext4"

Can you please tell me what I'm doing wrong ?

Thanks.

**Comment by E-Gwen** [comment]
Hey, wait a moment !
I forgot "userdata" in the command line "fastboot flash userdata %systemdrive%%homepath%\Downloads\asteroid-image-*.ext4"

Be careful, Windows newbies users !

I made it !

Can't wait the AsteroidOS 2.0 version !

Have a nice watch ! See you !
