### ISSUE TITLE
Command "fasboot continue" forgot : smartwatch endless restarting

### ISSUE THREAD

**Issue by E-Gwen** [AsteroidOS/asteroidos.org#208]
Hi,

Instead of typing "fastboot continue" at the end of the flashing process, i wrote "exit" at the "command line".

So now the smartwatch is restarting endlessly.

Can you tell me what i am supossed to do now to recover the smartwatch at a right state ?

Regards.

**Comment by dodoradio** [comment]
what watch are you using? at https://asteroidos.org/wiki/useful-commands/#boot-to-fastboot-bootloader-menu there are instructions for getting back to fastboot - power off your watch by holding the power button, then try the instructions appropriate for your watch

**Comment by eLtMosen** [comment]
This was resolved in the matrix chat and @E-Gwen has a working sparrow now ;)
