### ISSUE TITLE
A page with things people are working on

### ISSUE THREAD

**Issue by lepras** [AsteroidOS/asteroidos.org#209]
Currently one has to skim through chats and github issues of AOS repos. But people have their own personal projects in their id's and one can not get a bird's eye view of things.

Things I think we should mention:

1. title
2. people working on it
3. phase of project
4. "This is an open source project so people are only giving their free time so no ETA's please" (If you want to give money etc etc :P)

**Comment by eLtMosen** [comment]
I believe that implementing a system where titles, people involved, and project phases are publicly displayed might inadvertently create unnecessary accountability and pressure on contributors. As an open-source project, it's important to respect the fact that individuals are dedicating their free time to contribute. Introducing expectations may discourage potential contributors or lead to dissatisfaction among the current ones.

Instead, I suggest we focus on maintaining an open and collaborative environment where contributors can freely choose when and if they want to share information about their personal projects. It's crucial to respect their autonomy and allow them to decide what they are comfortable disclosing.  Currently, collaboration primarily happens on Matrix, where contributors can freely exchange ideas and engage in discussions and give updates on what they are doing currently.
