### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by tambry** [AsteroidOS/asteroidos.org#21]
The website is inaccessible over IPv6.

**Comment by FlorentRevest** [comment]
Maybe @ledixus knows if that would be easy to fix?

**Comment by ledixus** [comment]
Too busy the last time, I'm working for the IPv6 support.

**Comment by beroset** [comment]
I just tried it and it appears to working just fine.  It resolves to 2a01:4f8:192:63d0::2
Shall we close this?

**Comment by tambry** [comment]
Yes, seems to have been fixed at some point.
