### ISSUE TITLE
Show info panel for lenok for heart rate sensor

### ISSUE THREAD

**Issue by GeckoEidechse** [AsteroidOS/asteroidos.org#238]
As discovered in https://github.com/AsteroidOS/meta-smartwatch/issues/159 and https://github.com/AsteroidOS/meta-smartwatch/issues/55 one might need to update lenok to a newer firmware in order to get the heart rate sensor to work in AsteroidOS.

https://github.com/AsteroidOS/meta-smartwatch/issues/159 should contain all the necessary info/steps in order to get it working but we should still put up an info panel similar to the one we have for [`bass`](https://asteroidos.org/install/bass/)

**Comment by MagneFire** [comment]
The info panel has been added via: https://github.com/AsteroidOS/asteroidos.org/pull/239.
