### ISSUE TITLE
"Concentrate more on content rather than infrastructure." - beroset

### ISSUE THREAD

**Issue by lepras** [AsteroidOS/asteroidos.org#277]
Discussion on next steps for systematizing the wiki and making it more automated and just focusing on content not js modules. I think for us static site generation is best. 

I elect https://nextra.site/

**Comment by beroset** [comment]
I think my preference would be to use mediawiki:  https://www.mediawiki.org/wiki/MediaWiki

**Comment by lepras** [comment]
> I think my preference would be to use mediawiki: https://www.mediawiki.org/wiki/MediaWiki

I tried mirahaze (mediawiki hosting provider) once, its pretty great.

**Comment by beroset** [comment]
Since we now have a fully implemented [wiki](https://wiki.asteroidos.org/index.php/Documentation),  I'm closing this one.
