### ISSUE TITLE
Slug is either too high or not centered to the mean line of the title

### ISSUE THREAD

**Issue by eLtMosen** [AsteroidOS/asteroidos.org#343]
![image](https://user-images.githubusercontent.com/15074193/230767316-ec831903-d2a8-465e-9de8-5537070dd3fe.png)

**Comment by eLtMosen** [comment]
I'd say it needs to be centered to the `()`
![image](https://user-images.githubusercontent.com/15074193/230803249-bf4f7334-9032-48ba-8e00-d526dc220281.png)

**Comment by eLtMosen** [comment]
@MagneFire @FlorentRevest opinions on this?

- The slug is an svg and i would first of all remove the svg code into a svg file
- I would try to make look the slug consistent to the `()` in height, linewidth and vertical centering to the font mean line.

Practically, it will become a bit thicker and likely a tad taller to be as high as the `()`. 

Also, while i have you here, look at the (catfish/catfish_ext/catshark) cluster. It is visually quite appealing. But breaks the mobile view since its too wide and forces the viewport width to scroll horizontally.
https://github.com/AsteroidOS/asteroidos.org/issues/329

On that, i'd like to make the `, ` and ` / ` consistent with spacings properly used like in text grammar. And implement that over the whole website. This would impact the watches gallery page too for the comma separated multiple codename/variant watches.

**Comment by MagneFire** [comment]
> @MagneFire @FlorentRevest opinions on this?
> 
>     * The slug is an svg and i would first of all remove the svg code into a svg file
> 
>     * I would try to make look the slug consistent to the `()` in height, linewidth and vertical centering to the font mean line.
> 
> 
> Practically, it will become a bit thicker and likely a tad taller to be as high as the `()`.

I'm fine with it being a bit thicker. Making it consistent with the brackets seems the more important part imho.

> 
> Also, while i have you here, look at the (catfish/catfish_ext/catshark) cluster. It is visually quite appealing. But breaks the mobile view since its too wide and forces the viewport width to scroll horizontally. #329
> 
> On that, i'd like to make the `, ` and `/` consistent with spacings properly used like in text grammar. And implement that over the whole website. This would impact the watches gallery page too for the comma separated multiple codename/variant watches.

We could also remove the codename from the header since there's already a table below it containing the watch codenames. Else the idea of using consistent spacing a good idea as well.
Having the watches page comma separated looks just as good to me:
![image](https://user-images.githubusercontent.com/7857908/230914604-22f6c92e-8433-4ef4-9fa1-5e4945b7e5a4.png)

**Comment by eLtMosen** [comment]
Following up on the slug issue, i found that the char is acually part of unicode  and maybe we should just use one of those present in the OpenSans font.

![grafik](https://user-images.githubusercontent.com/15074193/231501212-511da412-6d6b-4fcf-9ad4-1c29175bc1e5.png)
![grafik](https://user-images.githubusercontent.com/15074193/231501268-7de728cb-6cc9-4aaf-9ad3-36547864f2f3.png)
![grafik](https://user-images.githubusercontent.com/15074193/231501292-abefcb84-ccbe-4dda-a5eb-75f5ef9fd3e5.png)

I favour the last one since it looks best in line with the OpenSans ` / 
`
