### ISSUE TITLE
[Install Troubleshoot] Advise to update WearOS to the latest available version

### ISSUE THREAD

**Issue by eLtMosen** [AsteroidOS/asteroidos.org#374]
@ lordpaxed in matrix chat has malfunctioning sensors on a beluga that are possibly caused by too old android base.
It might be a possibly noteworthy troubleshoot step for ll watches to update o the latest available WearOS.
Since on used watches, we never know the state at purchase.

**Comment by MagneFire** [comment]
This is not the issue here as we mount the `vendor` and `system` partitions as opposed to providing our own Android base (`bass` era of devices).

Leaving open until we have more information.
