### ISSUE TITLE
Nightlies FTP folder is not accessible anymore

### ISSUE THREAD

**Issue by asozcan** [AsteroidOS/asteroidos.org#396]
`nightlies` folder at https://release.asteroidos.org/ throwing nginx 404. I am not able to download files for ray from anywhere, asteroid-image-ray.ext4. Can someone help me, is there anyone keeping copies of `ray.ext4` and `ray.fastboot` ?

**Comment by asozcan** [comment]
Nevermind, I found that it is an intentional down to prevent bricks. Let's wait for the fix 🤞

**Comment by MagneFire** [comment]
The nightlies are now available again.
