### ISSUE TITLE
https://asteroidos.org/ Down

### ISSUE THREAD

**Issue by andronedev** [AsteroidOS/asteroidos.org#420]
https://asteroidos.org/ is down

**Comment by MagneFire** [comment]
It seems to work fine for me.
Checking sites like https://downforeveryoneorjustme.com/asteroidos.org also return the expected.

Maybe it was some minor outage? Can you check if it works for you now?

**Comment by andronedev** [comment]
strange I have the error code ERR_TIMED_OUT

**Comment by beroset** [comment]
@andronedev Are you still experiencing problems?
