### ISSUE TITLE
incorrect compiler name in documentation, links

### ISSUE THREAD

**Issue by beroset** [AsteroidOS/asteroidos.org#53]
The 0e82dc2 patch (that I submitted!) was wrong and it should be reverted in its entirety.  The problem was that the build I was using.  Specifically, I had started atop an old build, pulled from the git repo and rebuild and inadvertently discovered a bug in git ( https://bugzilla.redhat.com/show_bug.cgi?id=1803506 ) as a byproduct.  I believe that was why my build differed.  Many thanks to @MagneFire for correctly questioning this pull request.  See https://github.com/AsteroidOS/asteroidos.org/pull/52/files

**Comment by FlorentRevest** [comment]
Cool! I should also have paid more attention to your previous PR, thanks!
