### ISSUE TITLE
[bass] LG boot loop after following section 2a of install instructions

### ISSUE THREAD

**Issue by jcstaudt** [AsteroidOS/asteroidos.org#55]
**Watch model:** bass
**AsteroidOS Image:** nightly
**Host OS:** Debian 10

After following section 2a of the installation instructions [here](https://asteroidos.org/install/bass/), my watch enters a boot loop where the LG logo appears on the screen, goes away and reappears, and so on.

I have had this issue in the past when i first loaded AsteroidOS on my watch, and reproduced it again today. The solution to this situation has been to run `fastboot flash boot ~/Downloads/zImage-dtb-bass.fastboot` prior to `fastboot flash userdata ~/Downloads/asteroid-image-bass.ext4`.

I see that this section of the page is generated within a layout template affecting many watches. Is this in fact the correct order for other watches and just doesn't work for bass? I'm asking because I don't want to submit a pull request in a way that makes the documentation work for my watch model and not for the other watch models.

**Comment by jrtberlin** [comment]
Are you sure you are not referring to `2a`? `2b` is the temporary install instruction where no partition gets flashed. 
The order should(TM) be irrelevant for the normal installation since boot and data are two different partitions. 
Have you tried `fastboot reboot` instead of `fastboot continue`?
In case you are really referring to `2b`:
You can't execute `fastboot boot ~/Downloads/zImage-dtb-bass.fastboot` prior to pushing the asteroid image since the boot (kernel) image then has nothing to boot.

**Comment by jcstaudt** [comment]
Thank you for your feedback!

> Are you sure you are not referring to `2a`? `2b` is the temporary install instruction where no partition gets flashed.

Oops. Yes, that's a typo. I mean `2a`. I edited the issue body to align with the title.

> The order should(TM) be irrelevant for the normal installation since boot and data are two different partitions.

I agree - that's what makes sense to me as well. However, the boot loop occurred after several attempts until I decided to reverse the order. I can only assume that there is additional logic to the command other than something resembling a `dd` command to overwrite the partition. Perhaps an enable flag gets set or a symlink/path is set. Somebody much more familiar than myself would have to confirm.

> Have you tried `fastboot reboot` instead of `fastboot continue`?

Hm.. no I haven't. I didn't even know about that!

**Comment by eLtMosen** [comment]
Closing since this is very likely a timing issue where the boot image and system image flash order swap where not related to fixing the flash issue. Very likely simply repeating the flash process did the trick like noted in our new install troubleshooting section.
