### ISSUE TITLE
Links to nightly builds are broken on the site.

### ISSUE THREAD

**Issue by Tanatcu** [AsteroidOS/asteroidos.org#57]
All links to builds are broken on https://asteroidos.org/ site. Every link leads to a 404 site error. As I understand, those files haven't been published to release.asteroid.org yet.
Could you provide a list of GitHub links to real files if they exist?

Thanks beforehand for an answer and for your great work!

**Comment by FlorentRevest** [comment]
We are migrating the server and new nightly builds are running.
There are non equivalent files available to download on GitHub. If you are impatient, you can compile Asteroid https://asteroidos.org/wiki/building-asteroidos/ :)

**Comment by FlorentRevest** [comment]
Thanks, this is fixed now :) https://release.asteroidos.org/nightlies/
