### ISSUE TITLE
Change watch rating

### ISSUE THREAD

**Issue by MagneFire** [AsteroidOS/asteroidos.org#80]
The recommended watches are the LG G Watch Urbane (bass) and the Huawei Watch (sturgeon).

Simply looking at the install page(https://asteroidos.org/install/) does not highlight this.

I think we should come up with a better method to distinguish the most recommended watches.

I purpose the following two changes:

#### Move to five star rating

Currently, there are watches that have the 3 stars while not being on-par with bass and sturgeon (harmony and smelt).
While others have 2 stars but have some essential features missing (swift, mooneye) others seems perfectly capable (wren, sparrow).

What do you think of the following:
1 star (horrible, has some serious issues): tetra
2 stars (ok, but missing some essential features (Bluetooth)): swift, mooneye
3 stars (good, but misses some great features (Always-on-Display, Tilt-to-wake, etc)): anthias, dory, (in)harmony
4 stars (Great, minor things are missing (microphone)): smelt, lenok, sparrow, wren
5 Excellent (No missing features): bass, sturgeon

#### Change watch order to star based

Instead of alphabetically ordering the watches. The best supported watches will be the first in the list, no need to scroll down.

Please let me know what you think of this. Other suggestions are also welcome :wink:

**Comment by FlorentRevest** [comment]
I'm all in for that :)

**Comment by jrtberlin** [comment]
I think both proposals are a good idea.

**Comment by MagneFire** [comment]
As per: https://github.com/AsteroidOS/asteroidos.org/commit/1509f09e598ed83ba92d745437fb335a20a7e6f8 this has been realized.
